services:
  db:
    env_file:
      - path: ./.env
        required: true
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    ports:
      - "${SERVER_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${SERVER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SERVER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SERVER_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    env_file:
      - path: ./.env
        required: true
    image: valkey/valkey:8.1
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      VALKEY_PASSWORD: ${SERVER_VALKEY_PASSWORD}
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--requirepass", "${SERVER_VALKEY_PASSWORD}"]

volumes:
  postgres_data:
  valkey_data:
