// This file is @generated by prost-build.
/// / Request to spawn a new combat unit.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnUnitRequest {}
/// / Response after attempting to spawn a unit.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnUnitResponse {}
/// / Request to list all units owned by a player.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListUnitsRequest {}
/// / Response containing a list of the player's units.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUnitsResponse {
    /// / List of units owned by the player.
    #[prost(message, repeated, tag = "1")]
    pub units: ::prost::alloc::vec::Vec<Unit>,
}
/// / Represents a single unit in the game.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unit {
    /// / UUID of the unit.
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// / UUID of the user who owns the unit.
    #[prost(string, tag = "2")]
    pub user_uuid: ::prost::alloc::string::String,
}
