// This file is @generated by prost-build.
/// / Request to get the player's corporation details.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCorporationRequest {}
/// / Response containing corporation details.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCorporationResponse {
    /// / Corporation owned by the player.
    #[prost(message, optional, tag = "1")]
    pub corporation: ::core::option::Option<Corporation>,
}
/// / Represents a player's corporation in the game.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Corporation {
    /// / UUID of the corporation.
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// / UUID of the user who owns the corporation.
    #[prost(string, tag = "2")]
    pub user_uuid: ::prost::alloc::string::String,
    /// / Name of the corporation.
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// / Current balance or funds available.
    #[prost(int64, tag = "4")]
    pub balance: i64,
}
