// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnUnitRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnUnitResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListUnitsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUnitsResponse {
    #[prost(message, repeated, tag = "1")]
    pub units: ::prost::alloc::vec::Vec<UnitInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnitInfo {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_uuid: ::prost::alloc::string::String,
}
