// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCorporationRequest {
    #[prost(string, tag = "1")]
    pub session_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCorporationResponse {
    #[prost(message, optional, tag = "1")]
    pub corporation: ::core::option::Option<CorporationInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CorporationInfo {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub balance: i64,
}
