name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: syndicode-server/Dockerfile
          push: true
          tags: mbuse0/syndicode-server:${{ env.RELEASE_TAG }}

      - name: Prepare Helm update output
        run: |
          mkdir -p output/
          echo "server:" > output/Values.yaml
          echo "  container:" >> output/Values.yaml
          echo "    image: \"mbuse0/syndicode-server:${RELEASE_TAG}\"" >> output/Values.yaml

      - name: Push image tag to config repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "output"
          destination-github-username: "MaikBuse"
          destination-repository-name: "pub-talos-cluster"
          target-branch: "main"
          target-directory: "helm/syndicode/server"
          commit-message: "Update syndicode-server image tag to ${{ env.RELEASE_TAG }}"
