name: Rust CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Format check
        run: cargo fmt --manifest-path syndicode-server/Cargo.toml -- --check

      - name: Lint (clippy)
        run: cargo clippy --manifest-path syndicode-server/Cargo.toml --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo check --manifest-path syndicode-server/Cargo.toml --all-targets

      - name: Test
        run: cargo test --manifest-path syndicode-server/Cargo.toml --all-targets --all-features
