name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable

      - name: Check formatting
        run: cargo fmt --manifest-path syndicode-server/Cargo.toml -- --check

      - name: Lint with Clippy
        run: cargo clippy --manifest-path syndicode-server/Cargo.toml --all-targets --all-features -- -D warnings

      - name: Build syndicode-server
        run: cargo build --manifest-path syndicode-server/Cargo.toml --verbose

      - name: Run tests for syndicode-server
        run: cargo test --manifest-path syndicode-server/Cargo.toml --verbose
