name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Build & Test syndicode-server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --manifest-path syndicode-server/Cargo.toml -- --check

      - name: Lint with Clippy
        run: cargo clippy --manifest-path syndicode-server/Cargo.toml --all-targets --all-features

      - name: Build
        run: cargo build --manifest-path syndicode-server/Cargo.toml --verbose

      - name: Run tests
        run: cargo test --manifest-path syndicode-server/Cargo.toml --verbose
