name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        run: cargo fmt --package syndicode-server --package syndicode-client -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  server-unit-tests:
    name: Server Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-debug-
      - name: Run Server Unit Tests
        run: cargo test -p syndicode-server

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, server-unit-tests]
    services:
      postgres:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: syndicode
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      valkey:
        image: valkey/valkey:8.1
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install PostgreSQL Client v17
        run: |
          # Remove any existing PostgreSQL installations to avoid conflicts
          sudo apt-get remove -y postgresql-client-* || true
          
          # Add the PostgreSQL GPG key and repository
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates gnupg
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
          
          # Update and install the client
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          
          # Force the system to use PostgreSQL 17 binaries
          sudo update-alternatives --install /usr/bin/pg_restore pg_restore /usr/lib/postgresql/17/bin/pg_restore 100
          sudo update-alternatives --install /usr/bin/psql psql /usr/lib/postgresql/17/bin/psql 100
          sudo update-alternatives --install /usr/bin/pg_dump pg_dump /usr/lib/postgresql/17/bin/pg_dump 100
          
          # Verify the installation
          which pg_restore
          pg_restore --version
          echo "PostgreSQL 17 client tools installed successfully"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-

      - name: Build server and client
        run: cargo build --workspace --release
        env:
          SQLX_OFFLINE: true

      - name: Start server in background
        run: ./target/release/syndicode-server --restore $SERVER_DB_DUMP_URL &> server.log &
        env:
          # Cargo
          RUST_LOG: "syndicode_client=debug,syndicode_server=info,info"
          RUST_BACKTRACE: 1

          # Server Configuration
          SERVER_DISABLE_RATE_LIMITING: true
          SERVER_DB_DUMP_URL: ${{ vars.SERVER_DB_DUMP_URL }}

          # Intentiaoally leave the password empty
          SERVER_VALKEY_PASSWORD: ""

          SERVER_SMTP_SERVER: ${{ secrets.SERVER_SMTP_SERVER }}
          SERVER_SMTP_USERNAME: ${{ secrets.SERVER_SMTP_USERNAME }}
          SERVER_SMTP_PASSWORD: ${{ secrets.SERVER_SMTP_PASSWORD }}

      - name: Install gRPC Health Probe
        run: |
          GRPC_HEALTH_PROBE_VERSION=v0.4.26
          wget -qO /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64
          chmod +x /usr/local/bin/grpc_health_probe

      - name: Wait for server health (gRPC)
        run: |
          echo "Waiting for gRPC server to start..."
          for i in {1..60}; do
            if grpc_health_probe -addr=localhost:50051; then
              echo "gRPC Server is healthy!"
              exit 0
            fi
            sleep 1
          done
          echo "gRPC Server failed to start in 30 seconds."
          echo "--- Server Logs ---"
          cat server.log
          exit 1

      - name: Run Client Integration Tests
        run: cargo test -p syndicode-client -- --test-threads=1
        env:
          CLIENT_IS_LOCAL_TEST: true
          CLIENT_SERVER_ADDRESS: http://localhost:50051

      - name: Stop server
        if: always()
        run: |
          echo "Stopping server..."
          pkill syndicode-server || echo "Server was not running."
